

SET SERVEROUTPUT ON;

BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE employee CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


BEGIN
    EXECUTE IMMEDIATE 'DROP TABLE department CASCADE CONSTRAINTS';
EXCEPTION
    WHEN OTHERS THEN
        IF SQLCODE != -942 THEN
            RAISE;
        END IF;
END;
/


CREATE TABLE department (
    department_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    department_name VARCHAR2(100) NOT NULL,
    CONSTRAINT pk_department PRIMARY KEY (department_id)
);



CREATE TABLE employee (
    employee_id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    employee_name VARCHAR2(100) NOT NULL,
    salary NUMBER(12,2) NOT NULL,
    hire_date DATE NOT NULL,
    department_id NUMBER,
    CONSTRAINT pk_employee PRIMARY KEY (employee_id),
    CONSTRAINT fk_employee_department
        FOREIGN KEY (department_id)
        REFERENCES department(department_id)
);



INSERT INTO department (department_name)
VALUES ('Information Technology');

INSERT INTO department (department_name)
VALUES ('Finance');

INSERT INTO department (department_name)
VALUES ('Human Resources');

INSERT INTO department (department_name)
VALUES ('Marketing');



INSERT INTO employee
(employee_name, salary, hire_date, department_id)
VALUES
('John Doe', 500000, DATE '2020-01-15', 1);

INSERT INTO employee
(employee_name, salary, hire_date, department_id)
VALUES
('Jane Smith', 650000, DATE '2018-06-10', 2);

INSERT INTO employee
(employee_name, salary, hire_date, department_id)
VALUES
('Peter Johnson', 450000, DATE '2022-03-20', 3);

INSERT INTO employee
(employee_name, salary, hire_date, department_id)
VALUES
('Mary Williams', 800000, DATE '2017-09-05', 1);

INSERT INTO employee
(employee_name, salary, hire_date, department_id)
VALUES
('David Brown', 550000, DATE '2021-11-12', 4);

COMMIT;



SELECT * FROM department;

SELECT * FROM employee;